FROM node:16.16.0-alpine3.15
RUN apk update
RUN \
    apk add --no-cache gcc python3 make g++ automake autoconf libtool nasm shadow musl-dev tiff jpeg zlib zlib-dev file pkgconf && \
    apk add vips-dev fftw-dev --no-cache --repository http://dl-3.alpinelinux.org/alpine/v3.10/community --repository http://dl-3.alpinelinux.org/alpine/v3.10/main vips-dev && \
    rm -fR /var/cache/apk/*
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

COPY bomberland-library/package.json /app/bomberland-library/package.json
COPY bomberland-library/tsconfig.json /app/bomberland-library/tsconfig.json

COPY ./bomberland-engine/package.json /app/bomberland-engine/package.json

WORKDIR /app
RUN yarn install

WORKDIR /app/bomberland-library
ENV ENVIRONMENT=dev
ENTRYPOINT yarn build && cd ../bomberland-engine && yarn install && yarn run start
